/**
 * Cheltenham Hackspace Environmental Monitoring Dashboard
 * Public map page entry point
 */
import { initNav } from '../../lib/ui.js';
import { API_BASE } from '../../lib/config.js';
import { Utils } from '../../lib/utils.js';
import { AppState } from './state.js';
import { MapManager } from './map-view.js';
import { ChartManager } from './charts.js';
import { DataManager } from './data.js';

initNav('map');

// Event handlers
function toggleDataset(dataset) {
    const checkbox = document.getElementById(`${dataset}-toggle`);
    if (!checkbox) return;

    if (checkbox.checked) {
        if (!AppState.selectedDatasets.includes(dataset)) {
            AppState.selectedDatasets.push(dataset);
        }
    } else {
        AppState.selectedDatasets = AppState.selectedDatasets.filter(d => d !== dataset);
    }

    if (AppState.deviceId) {
        DataManager.fetchSensorData();
    }
}

function setTimespan(value) {
    const newTimespan = parseInt(value);
    if (newTimespan !== AppState.timespan) {
        AppState.timespan = newTimespan;
        if (AppState.deviceId) {
            DataManager.fetchSensorData();
        }
    }
}

function refreshData() {
    // Clear relevant cache entries to force fresh data
    if (AppState.deviceId) {
        const cacheKey = `${AppState.deviceId}_${AppState.timespan}`;
        AppState.cache.sensorData.delete(cacheKey);
        AppState.cache.lastFetch.delete(cacheKey);
        DataManager.fetchSensorData();
    }

    // Also refresh sensor list
    AppState.cache.sensors = null;
    AppState.cache.lastFetch.delete('sensors');
    DataManager.fetchSensors();

    Utils.showNotification('Data refreshed', 'success');
}

function downloadData() {
    if (!AppState.deviceId) {
        Utils.showNotification('Please select a sensor first', 'warning');
        return;
    }

    const range = Utils.roundTimeRange(Date.now() - AppState.timespan, Date.now());
    const url = `${API_BASE}/sensor/${AppState.deviceId}/download?from=${range.from}&to=${range.to}`;
    const link = document.createElement('a');
    link.href = url;
    link.download = `sensor_${AppState.deviceId}_data.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    Utils.showNotification('Download started', 'success');
}

// Application initialization
function initializeApp() {
    // Initialize components
    MapManager.init();
    ChartManager.init();

    // Load initial data
    DataManager.fetchSensors();

    // Set up periodic cache cleanup
    setInterval(() => {
        DataManager.cleanupCache();
    }, 10 * 60 * 1000); // Every 10 minutes

    // Set up periodic data refresh for active sensor
    setInterval(() => {
        if (AppState.deviceId) {
            // Only refresh if cache is expired
            const cacheKey = `${AppState.deviceId}_${AppState.timespan}`;
            if (!DataManager.isCacheValid(cacheKey)) {
                DataManager.fetchSensorData();
            }
        }
    }, 2 * 60 * 1000); // Every 2 minutes

    console.log('Environmental Monitoring Dashboard initialized');
}

// Initialize when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initializeApp);
} else {
    initializeApp();
}

// Bridges for the inline on* handlers in index.html (and HTML generated by
// the modules). Removing the inline handlers entirely is future polish.
window.toggleDataset = toggleDataset;
window.setTimespan = setTimespan;
window.refreshData = refreshData;
window.downloadData = downloadData;
window.toggleHeatmap = MapManager.toggleHeatmap;
window.AppState = AppState;
window.DataManager = DataManager;
